package com.example.hp.ecodriveapplication.models;

import android.net.Uri;
import android.support.annotation.NonNull;
import android.util.Log;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.GeoPoint;


public class UserDetails {
    public String userId;
    public String name;
    public String emailAddress;
    public String gender;
    public String nickName;
    public String phoneNumber;
    public GeoPoint geoPoint;
    public Uri imageUri;
    public String circleId; //use add() for autoGeneratedId in firestore

    public static UserDetails userDetails;

    public static UserDetails getUserDetails() {
        return userDetails;
    }

    public static void setUserDetails(UserDetails userDetails) {
        UserDetails.userDetails = userDetails;
    }

    private UserDetails(){ } //private Constructor

    public static UserDetails getInstance()
    {
        if(userDetails==null)
        {
            userDetails=new UserDetails();//(emailAddress,name,password,nickName,phoneNumber);
            return userDetails;
        }
        else
            return userDetails;
    }

    public String getCircleId() { return circleId; }

    public void setCircleId(String circleId) { this.circleId = circleId; }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Uri getImageUri() {
        return imageUri;
    }

    public void setImageUri(Uri imageUri) {
        this.imageUri = imageUri;
    }

    public String getUserId() { return userId; }

    public void setUserId(String userId) {
        this.userId = userId;
    }


    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public GeoPoint getGeoPoint() {
        return geoPoint;
    }

    public void setGeoPoint(GeoPoint geoPoint) {
        this.geoPoint = geoPoint;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public void updateFirestoreInstance(DocumentReference documentReference)
    {
        documentReference.set(userDetails).addOnCompleteListener(new OnCompleteListener<Void>() {
            @Override
            public void onComplete(@NonNull Task<Void> task) {
                if(task.isSuccessful()) {
                    Log.d(Constants.USERTAG, "user details uploaded successfully");
                }
                else
                    Log.d(Constants.USERTAG, "user details failed to upload");
            }
        });
    }





}
